### PR TITLE
Add FTW Project

### PR DESCRIPTION
**Pull request by forthewinproject**

### CODE REVIEW

**Comment by chenzhitong** [comment]
Is your project an open source project? Do you have GitHub links? @forthewinproject

**Comment by forthewinproject** [comment]
We have been working on a private repo. Planning to open partially in the future.

**Comment by chenzhitong** [comment]
Now the audit is strict, need to have the public GitHub link. @forthewinproject

**Comment by forthewinproject** [comment]
Okay. Thanks.

**Pull request closed without merging**
