### PR TITLE
Spotcoin Addition

### PR DESCRIPTION
**Pull request by kurisu1996**

### CODE REVIEW

**Comment by chenzhitong** [comment]
Is there a github link to this project? @kurisu1996

**Comment by kurisu1996** [comment]
@chenzhitong As of now, Spotcoin's GitHub is private.

**Comment by chenzhitong** [comment]
Now the audit is strict, need to have a public GitHub link to be able to audit through. @kurisu1996

**Comment by kurisu1996** [comment]
@chenzhitong Understood. I will reapply for its addition once the code is made available to the public.

**Pull request closed without merging**
